# Generated by Django 2.0.4 on 2018-04-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_constant', models.FloatField(help_text='Real part of the constant used to define the julia set', verbose_name='Real Constant')),
                ('imaginary_constant', models.FloatField(help_text='Imaginary part of the constant used to define the julia set', verbose_name='Imaginary Constant')),
                ('depth', models.IntegerField(default=256, verbose_name='Iteration Depth')),
                ('resolution', models.IntegerField(default=512, help_text='A squared image with the value as side length is created', verbose_name='Resolution [px]')),
                ('colormap', models.CharField(choices=[('nipy_spectral', 'Nipy Spectral'), ('cubehelix', 'Cubehelix'), ('Oranges', 'Orange'), ('gnuplot', 'Gnuplot'), ('terrain', 'Terrain'), ('ocean', 'Ocean')], default='nipy_spectral', max_length=20)),
                ('image', models.FileField(blank=True, default='default.png', null=True, upload_to='')),
            ],
        ),
    ]
