# Generated by Django 2.0.4 on 2018-04-10 16:24

from django.db import migrations, models
import django.db.models.deletion

def initialize_computations(apps, schema_editor):
    Configuration = apps.get_model('fractals', 'Configuration')
    Computation = apps.get_model('fractals', 'Computation')

    for configuration in Configuration.objects.all():
        Computation.objects.create(
            configuration=configuration,
            image='abc.png',
            computing=False
        )


class Migration(migrations.Migration):

    dependencies = [
        ('fractals', '0005_auto_20180410_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('computing', models.BooleanField()),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computations', to='fractals.Configuration')),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='configuration',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.RunPython(initialize_computations, migrations.RunPython.noop)
    ]
