# Generated by Django 2.0.4 on 2018-04-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fractals', '0006_auto_20180410_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='computation',
            name='task_id',
            field=models.CharField(default='1', max_length=36),
            preserve_default=False,
        ),
    ]
